version: "3.8"
services:
  cinemagram-redis:
    container_name: cinemagram-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: kleahwang/cinemagram-redis
    ports:
      - "6379:6379"
  cinemagram-database:
    container_name: cinemagram-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: kleahwang/cinemagram-database
    environment:
      - MYSQL_DATABASE=cinemagram
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"