spring:
  profiles:
    active: local #default
    group:
      local:
        - common
        - oauth # include the oauth profile in the local profile
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common


---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/cinemagram
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update # create none validate update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 3MB

file:
  path: C:/Users/dbwjd/Desktop/Projects/ImageUpload/


---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cinemagram-database:3307/cinemagram
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: cinemagram-redis
    port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

